<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>GeniaPassword</RootNamespace>
		<NoWarn>$(NoWarn);CA1416</NoWarn>
		<AssemblyName>GeniaPassword</AssemblyName>
		<AssemblyTitle>GeniaPassword</AssemblyTitle>
		<Product>GeniaPassword</Product>
		<Description>Локальный портативный менеджер паролей</Description>
		<Version>2.1.1</Version>
		<AssemblyVersion>2.1.0.0</AssemblyVersion>
		<FileVersion>2.1.1.0</FileVersion>
		<ApplicationIcon>Assets\GeniaPassword.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<PublishTrimmed>false</PublishTrimmed>
		<PublishReadyToRun>false</PublishReadyToRun>
		<DebugSymbols>false</DebugSymbols>
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="TopSecret.Cryptography.Argon2" Version="2.2.0" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Assets\GeniaPassword.ico" LogicalName="GeniaPassword.ico" />
		<EmbeddedResource Include="THIRD_PARTY_NOTICES.txt" LogicalName="THIRD_PARTY_NOTICES.txt" />
	</ItemGroup>
</Project>